In [2]:
#Start Numpy
import numpy as np

In [3]:
data = [1,2,3,4,5] #Data list
data

[1, 2, 3, 4, 5]

In [4]:
np.array(data) #Mengubah list menjadi numpy array

array([1, 2, 3, 4, 5])

In [6]:
np.arange(0,10) #Membuat data array numpy secara otomatis

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2) #Membuat sebuah kelipatan (dengan patokan pada angka 2 diakhir)

array([0, 2, 4, 6, 8])

In [8]:
#Membuat array dummy
np.linspace(0,10,3) #3 diakhir merupakan patokan jumlah data

array([ 0.,  5., 10.])

In [9]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [10]:
np.random.rand(3) #3 adalah jumlah data random yang muncul berupa kolom

array([0.19464399, 0.37121962, 0.34165866])

In [13]:
np.random.rand(5,6) # 5 berupa baris, 6 berupa kolom. yang berisi data random

array([[0.65246134, 0.13027607, 0.76640541, 0.53469691, 0.02014348,
        0.21851454],
       [0.53863257, 0.08947247, 0.93683916, 0.93347589, 0.77568025,
        0.10536072],
       [0.83240167, 0.02750276, 0.37401234, 0.73112354, 0.26678964,
        0.22861407],
       [0.27272494, 0.18689992, 0.14250545, 0.67265801, 0.01357298,
        0.97139919],
       [0.9108086 , 0.9072769 , 0.70049997, 0.60134831, 0.66191332,
        0.80483975]])

In [14]:
np.random.randn(5,5) #rand{n} negatif dan positif

array([[ 2.14830676, -1.36456381,  0.04866258, -0.93657089,  0.49443152],
       [ 1.21806482, -1.16746007, -0.33674884, -2.53313819,  1.04844775],
       [-0.55238072, -0.25309153, -0.00699893, -0.56168178,  0.04759829],
       [-0.75357284,  0.92174495, -0.03835836,  0.48470509, -0.73372845],
       [ 0.94061657, -0.92887483,  0.96702188,  0.78569501,  1.04450307]])

In [15]:
np.random.randint(1,30) #membuat data array random bilangan bulat

23

In [16]:
np.random.randint(1,50,10)

array([ 6, 14, 30, 42,  1, 34, 30, 23, 29, 41])

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr.reshape(5,5) #Merubah tampilan array dari 1D menjadi 2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr.max() #Nilai array terbesar

24

In [21]:
arr.min() #Nilai array terkecil

0

In [22]:
arr.argmax() #Index paling terbesar

24

In [23]:
arr.argmin() #Index paling terkecil

0

In [24]:
arr.sum() #Menjumlahkan semua array

300